### PR TITLE
AWS SDK v3 upgrade

### PR DESCRIPTION
**Pull request by chris-armstrong**
Upgrade to AWS SDK v3

### CODE REVIEW

**Comment by kbanman** [comment]
I'd love to use this with SDKv3. Is there something holding up this change?

**Comment by chris-armstrong** [comment]
Just a failure of prioritisation on my own usage, and the need to release a new major version. It is also untested, so could push out a beta?

**Comment by chris-armstrong** [comment]
> I'd love to use this with SDKv3. Is there something holding up this change?

Please check out the new 1.0.0-alpha.0 version and let me know if it works for you!

**Comment by kbanman** [comment]
Nice, I've swapped over a module and all integration tests are passing. Great work!

**Pull request merged**
